# Default prefixes for internal ontology terms
internal_uri_prefixes:
  entity_type: "cai_type:"       # CoreAI internal type
  property: "cai_prop:"       # CoreAI internal property
  entity_instance: "cai_instance:" # For specific instances

# Mappings from external URIs to internal terms
# Format: "external_uri": "internal_term_or_full_uri"
class_mappings:
  "http://example.com/ontology#Person": "cai_type:Person"
  "http://example.com/ontology#City": "cai_type:City"
  "http://schema.org/Person": "cai_type:Person"
  "http://schema.org/City": "cai_type:City"
  "http://xmlns.com/foaf/0.1/Person": "cai_type:Person" # FOAF Person

property_mappings:
  "http://example.com/ontology#locatedIn": "cai_prop:locatedIn"
  "http://example.com/ontology#hasName": "cai_prop:name"
  "http://xmlns.com/foaf/0.1/name": "cai_prop:name"         # FOAF name
  "http://xmlns.com/foaf/0.1/firstName": "cai_prop:firstName"
  "http://xmlns.com/foaf/0.1/lastName": "cai_prop:lastName"
  "http://schema.org/name": "cai_prop:name"
  "http://schema.org/location": "cai_prop:location"       # Could map to locatedIn or a generic location property
  "http://schema.org/address": "cai_prop:address"
  "http://www.w3.org/2000/01/rdf-schema#label": "cai_prop:label" # rdfs:label

# Instance mappings (optional, if specific external instances need mapping to internal IDs)
# instance_mappings:
#   "http://dbpedia.org/resource/London": "cai_instance:London_UK"
