# configs/simulated_resources.yaml
# Example configuration for simulated hardware resources for the AI sandbox.
# This file is loaded by the ResourceAwarenessService.

simulated_hardware_profile:
  profile_name: "StandardAISandbox_v1"

  disk:
    space_gb: 10.0
    warning_threshold_percent: 80 # Start slowdowns when disk is 80% full (e.g., at 8GB usage for a 10GB disk)
    critical_threshold_percent: 95 # More severe slowdowns when disk is 95% full (e.g., at 9.5GB usage)
    lag_factor_warning: 1.5       # Operations become 1.5x slower in warning state
    lag_factor_critical: 3.0      # Operations become 3.0x slower in critical state

  cpu:
    cores: 2
    # clock_speed_ghz: 2.5 # Conceptual
    # utilization_limit_percent: 90 # Conceptual

  ram:
    ram_gb: 4.0
    # usage_warning_threshold_percent: 75 # Conceptual

  gpu_available: false
  # gpu_memory_gb: 0.0 # Conceptual, relevant if gpu_available is true
  # network_bandwidth_mbps: 100 # Conceptual
